### ISSUE TITLE
tmp.zip in root directory is not deleted

### ISSUE THREAD

**Issue by alexjeen** [NotCoffee418/s3-zip-upload#6]
Hi,

When using this module, there is a tmp.zip file in the zip file that can not be opened. Maybe the zip file can be deleted after the upload to S3?

**Comment by NotCoffee418** [comment]
That sounds like two things that shouldn't happen. I'll fix it in a bit and see if I can add a way to test it better. Thanks for reporting it.

**Comment by alexjeen** [comment]
Hi, the zip itself is being properly created (the module is working fine). However, I think the tmp.zip file should be created in a different folder then the where the repository is being exported (maybe export it in /tmp/tmp.zip) so it would not be in the resulting .zip file

**Comment by alexjeen** [comment]
Might be that this PR fixes it: https://github.com/NotCoffee418/s3-zip-upload/pull/7
I didnt test it yet though so might need more work

**Comment by NotCoffee418** [comment]
Thanks for the PR but I won't merge it since i have a fancier implementation ready to go.  
It will instead use the OS specific temp directory, create a zip there and remove it once done.  

I'm being held back by trying to do something fancy my windows setup isn't happy with, auto-generate a release version of the script on commit using husky.

**Comment by alexjeen** [comment]
Thanks, my bad, I did not really use GitHub actions before and now see that you can run them on multiple OSes, so my PR wouldnt work on some of them.

I tested 1.2 and the tmp.zip file is gone now. 

Thanks!
